---
title: "Analytical Skills"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
---
&nbsp;

**Technical  Software**

1. Python 

2. R/R Studio 

3. Tableau

4. Github

5. DataRobot

6. SPSS


&nbsp;

**Machine Learning and Statistics**

1. Machine Learning, Ensemble Learning

2. Parametric and Non-Parametric Statistics

3. Principal Component Analysis

4. Correlation Analysis

5. Data Visualization

&nbsp;

**Emprical Design** 

1. Framing problems within a machine learning and/or statistical context. 

2. Prepping data for a variety of analyses. 

3. Hypothesis testing with statistics. 

&nbsp;

**Other Highlights**

*Experience using Electronic Health Record Data to conduct empirical studies regarding human health.*

&nbsp;

*Peer-reviewed publications and abstracts across industries and health verticals.*

&nbsp;

*Worked with the White House, Department of Health and Human Services and the Centers for Disease Control on the national response to the COVID-19 Pandemic.* 

&nbsp;

*Built a daily custom hospitalization model and surge classifier for the state of West Virginia's COVID-19 joint task force*  

&nbsp;

*Real world experience building customized analytics programs and applied machine learning models to support multibillion dollar goals.* 

&nbsp;

*Experience building custom technical enablement content including walkthroughs, FAQs, tutorial notebooks, videos and full courses including assessments.*

&nbsp;

*High level experience working with data for academic, governmental and organizational purposes.*

&nbsp;

*Demonstrated ability to learn relevant software and coding languages as necessary.*

&nbsp;

*Ability to teach technical content to individuals of varying technical background.*


<link rel="stylesheet" href="style.css" type="text/css" />
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-91308049-1', 'auto');
  ga('send', 'pageview');

</script>



<!-- Go to www.addthis.com/dashboard to customize your tools --> <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-589036a8549be1ce"></script>

